print("Este es un documento de prueba, todos pueden editarlo")
print("hace hambre")
print("aro")
print ("sisas")
print("all girl the same") 
print("lucid dreams")
print("robbery")
print("leo is theriuan")
print("YO ESTUVE AQUI")
print ("yo no estuve aqui")
